name: indepthacademy
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Updated to the latest version
  shared_preferences: ^2.2.0  # Updated to the latest version
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.0  # Updated to the latest version
  flutter_inappwebview: ^6.0.0
  no_screenshot: ^0.2.0
  video_player: ^2.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0  # Updated to the latest version

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon_logo.png  # Path to your icon file
  remove_alpha: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
